<?php

namespace Howkins\Borica\Constants;

class ResponseCode
{
    const ERRORS = [
        '-1' => 'A mandatory request field is not filled in',
        '-2' => 'CGI request validation failed',
        '-3' => 'Acquirer host (TS) does not respond or wrong format of e-gateway response template file',
        '-4' => 'No connection to the acquirer host (TS)',
        '-5' => 'The acquirer host (TS) connection failed during transaction processing',
        '-6' => 'e-Gateway configuration error',
        '-7' => 'The acquirer host (TS) response is invalid, e.g. mandatory fields missing',
        '-10' => 'Error in the "Amount" request field',
        '-11' => 'Error in the "Currency" request field',
        '-12' => 'Error in the "Merchant ID" request field',
        '-13' => 'The referrer IP address (usually the merchant\'s IP) is not the one expected',
        '-15' => 'Error in the "RRN" request field',
        '-16' => 'Another transaction is being performed on the terminal',
        '-17' => 'The terminal is denied access to e-Gateway',
        '-19' => 'Error in the authentication information request or authentication failed.',
        '-20' => 'The permitted time interval (1 hour by default) between the transaction timestamp request field and the e-Gateway time was exceeded',
        '-21' => 'The transaction has already been executed',
        '-22' => 'Transaction contains invalid authentication in-formation',
        '-23' => 'Invalid transaction context',
        '-24' => 'Transaction context data mismatch',
        '-25' => 'Transaction confirmation state was canceled by user',
        '-26' => 'Invalid action BIN',
        '-27' => 'Invalid merchant name',
        '-28' => 'Invalid incoming addendum(s)',
        '-29' => 'Invalid/duplicate authentication reference',
        '-30' => 'Transaction was declined as fraud',
        '-31' => 'Transaction already in progress',
        '-32' => 'Duplicate declined transaction',
        '-33' => 'Customer authentication by random amount or verify one-time code in progress',
        '-40' => 'Client side transaction form in progress',
        '00' => 'Successfully completed',
        '01' => 'Refer to card issuer',
        '04' => 'PICK UP',
        '05' => 'Do not Honour',
        '06' => 'Error',
        '12' => 'Invalid transaction',
        '13' => 'Invalid amount',
        '14' => 'No such card',
        '15' => 'No such issuer',
        '17' => 'Customer cancellation',
        '30' => 'Format error',
        '35' => 'Pick-up, card acceptor contact acquirer',
        '36' => 'Pick up, card restricted',
        '37' => 'Pick up, call acquirer security',
        '38' => 'Pick up, Allowable PIN tries exceeded',
        '39' => 'No credit account',
        '40' => 'Requested function not supported',
        '41' => 'Pick up, lost card',
        '42' => 'No universal account',
        '43' => 'Pick up, stolen card',
        '54' => 'Expired card / target',
        '55' => 'Incorrect PIN',
        '56' => 'No card record',
        '57' => 'Transaction not permitted to cardholder',
        '58' => 'Transaction not permitted to terminal',
        '59' => 'Suspected fraud',
        '85' => 'No reason to decline',
        '88' => 'Cryptographic failure',
        '89' => 'Authentication failure',
        '91' => 'Issuer or switch is inoperative',
        '95' => 'Reconcile error / Auth Not found',
        '96' => 'System Malfunction',
    ];
}

